### ISSUE TITLE
More plotting

### ISSUE THREAD

**Issue by fhui28** [fhui28/CBFM#2]
termplot.CBFM for parametric plots; coefplot.CBFM; anything fancier like plot.gam for smooth functions?

**Comment by fhui28** [comment]
Should either make an option in main CBFM to turn this off and/or create a separate function to do this. I prefer the latter.

**Comment by chrishaak** [comment]
WRT to a separate function, are you thinking that it would operate on a
fitted CBFM model object?   i.e., one would run a model, and then could
generate the plotting object at any point afterward?  If so, then that
seems like a nice approach...

**Comment by fhui28** [comment]
Yes that's the plan!

**Comment by fhui28** [comment]
Done and now in postMEE branch. Will merge into main branch after manuscript is formally accepted somewhere.
